name = "loquevotan"
main = "worker/index.mjs"
compatibility_date = "2026-03-02"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/share/*", "/og/*", "/api/*"]

[vars]
SITE_URL = "https://loquevotan.es"
API_BACKEND_MODE = "auto"

[[d1_databases]]
binding = "DB"
database_name = "loquevotan"
database_id = "4366d72e-4a59-4407-926c-03bbe9005952"
