#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, "public", "data");
const DEFAULT_OUT = path.join(ROOT, "tmp", "cloudflare-d1-seed.sql");
const D1_SQL_BATCH_SIZE = Number.parseInt(process.env.D1_SQL_BATCH_SIZE || "25", 10);

function normalizeSearchToken(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function toSqlString(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function toSqlNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) ? String(n) : "NULL";
}

function toSqlJson(value) {
  try {
    return toSqlString(JSON.stringify(value ?? null));
  } catch {
    return "NULL";
  }
}

function parseArgs(argv) {
  const outIndex = argv.findIndex((a) => a === "--out");
  if (outIndex >= 0 && argv[outIndex + 1]) {
    return path.resolve(ROOT, argv[outIndex + 1]);
  }
  return DEFAULT_OUT;
}

async function readJson(filePath) {
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw);
}

async function appendInsert(outFile, table, columns, rows, batchSize = D1_SQL_BATCH_SIZE) {
  if (!rows.length) return;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const valuesSql = batch.map((row) => `(${row.join(", ")})`).join(",\n");
    const sql = `INSERT OR REPLACE INTO ${table} (${columns.join(", ")}) VALUES\n${valuesSql};\n`;
    await fs.appendFile(outFile, sql, "utf8");
  }
}

function scopeDataPaths(scopeId) {
  if (scopeId === "nacional") {
    return {
      manifest: path.join(DATA_DIR, "manifest_home.json"),
      meta: path.join(DATA_DIR, "votaciones_meta.json"),
    };
  }
  return {
    manifest: path.join(DATA_DIR, scopeId, "manifest_home.json"),
    meta: path.join(DATA_DIR, scopeId, "votaciones_meta.json"),
  };
}

async function main() {
  const outFile = parseArgs(process.argv.slice(2));
  await fs.mkdir(path.dirname(outFile), { recursive: true });

  const ambitos = await readJson(path.join(DATA_DIR, "ambitos.json"));
  const scopes = Array.isArray(ambitos?.ambitos) ? ambitos.ambitos : [];

  await fs.writeFile(
    outFile,
    [
      "-- Generated by scripts/cloudflare/build_d1_seed.mjs",
      "DELETE FROM scope_meta;",
      "DELETE FROM groups;",
      "DELETE FROM votaciones;",
      "DELETE FROM diputados;",
      "",
    ].join("\n"),
    "utf8"
  );

  const scopeRows = [];
  const groupRows = [];
  const voteRows = [];
  const dipRows = [];
  const summary = [];

  for (const scope of scopes) {
    const scopeId = String(scope?.id || "").trim().toLowerCase();
    if (!scopeId) continue;

    const paths = scopeDataPaths(scopeId);
    const [manifest, meta] = await Promise.all([readJson(paths.manifest), readJson(paths.meta)]);

    const scopeName = String(scope?.nombre || scopeId);
    const diputadosCount = Number(manifest?.stats?.diputados || 0);
    const votacionesCount = Number(manifest?.stats?.votaciones || 0);
    const votosCount = Number(manifest?.stats?.votos || 0);

    scopeRows.push([
      toSqlString(scopeId),
      toSqlString(scopeName),
      toSqlString(manifest?.updatedAt || null),
      toSqlNumber(diputadosCount),
      toSqlNumber(votacionesCount),
      toSqlNumber(votosCount),
    ]);

    const grupos = Array.isArray(meta?.grupos) ? meta.grupos : [];
    for (let g = 0; g < grupos.length; g++) {
      groupRows.push([
        toSqlString(scopeId),
        toSqlNumber(g),
        toSqlString(grupos[g] || ""),
      ]);
    }

    const votaciones = Array.isArray(meta?.votaciones) ? meta.votaciones : [];
    const votResults = Array.isArray(meta?.votResults) ? meta.votResults : [];
    const categorias = Array.isArray(meta?.categorias) ? meta.categorias : [];

    for (let i = 0; i < votaciones.length; i++) {
      const vote = votaciones[i] || {};
      const result = votResults[i] || {};
      const categoriaIdx = Number.isInteger(vote.categoria) ? vote.categoria : null;
      const categoriaLabel = categoriaIdx !== null ? categorias[categoriaIdx] || null : null;
      voteRows.push([
        toSqlString(scopeId),
        toSqlNumber(i),
        toSqlString(vote.id || ""),
        toSqlString(vote.legislatura || null),
        toSqlString(vote.fecha || null),
        toSqlString(vote.titulo_ciudadano || ""),
        toSqlNumber(categoriaIdx),
        toSqlString(categoriaLabel),
        toSqlJson(Array.isArray(vote.etiquetas) ? vote.etiquetas : []),
        toSqlString(vote.proponente || ""),
        toSqlString(vote.subTipo || null),
        toSqlString(vote.exp || null),
        toSqlString(result.result || null),
        toSqlNumber(result.favor),
        toSqlNumber(result.contra),
        toSqlNumber(result.abstencion),
        toSqlNumber(result.total),
      ]);
    }

    const diputados = Array.isArray(meta?.diputados) ? meta.diputados : [];
    const dipStats = Array.isArray(meta?.dipStats) ? meta.dipStats : [];
    const dipFotos = Array.isArray(meta?.dipFotos) ? meta.dipFotos : [];
    const dipProvincias = Array.isArray(meta?.dipProvincias) ? meta.dipProvincias : [];

    for (let i = 0; i < diputados.length; i++) {
      const nombre = String(diputados[i] || "");
      const stats = dipStats[i] || {};
      const groupIdx = Number.isInteger(stats?.mainGrupo) ? stats.mainGrupo : null;
      dipRows.push([
        toSqlString(scopeId),
        toSqlNumber(i),
        toSqlString(nombre),
        toSqlString(normalizeSearchToken(nombre)),
        toSqlNumber(groupIdx),
        toSqlString(groupIdx !== null ? grupos[groupIdx] || null : null),
        toSqlNumber(stats.total),
        toSqlNumber(stats.favor),
        toSqlNumber(stats.contra),
        toSqlNumber(stats.abstencion),
        toSqlNumber(stats.no_vota),
        toSqlNumber(stats.loyalty),
        toSqlJson(dipFotos[i] ?? null),
        toSqlString(dipProvincias[i] || null),
      ]);
    }

    summary.push({
      scope: scopeId,
      votaciones: votaciones.length,
      diputados: diputados.length,
      grupos: grupos.length,
    });
  }

  await appendInsert(
    outFile,
    "scope_meta",
    ["scope_id", "scope_name", "updated_at", "diputados_count", "votaciones_count", "votos_count"],
    scopeRows
  );
  await appendInsert(outFile, "groups", ["scope_id", "group_idx", "group_name"], groupRows);
  await appendInsert(
    outFile,
    "votaciones",
    [
      "scope_id",
      "vot_idx",
      "id",
      "legislatura",
      "fecha",
      "titulo_ciudadano",
      "categoria_idx",
      "categoria_label",
      "etiquetas_json",
      "proponente",
      "sub_tipo",
      "expediente",
      "result",
      "favor",
      "contra",
      "abstencion",
      "total",
    ],
    voteRows
  );
  await appendInsert(
    outFile,
    "diputados",
    [
      "scope_id",
      "dip_idx",
      "nombre",
      "nombre_search",
      "main_grupo_idx",
      "main_grupo_name",
      "total",
      "favor",
      "contra",
      "abstencion",
      "no_vota",
      "loyalty",
      "foto_json",
      "provincia",
    ],
    dipRows
  );

  const stats = await fs.stat(outFile);
  console.log(`[cf-d1-seed] SQL generado: ${outFile}`);
  console.log(`[cf-d1-seed] tamaño: ${(stats.size / 1024 / 1024).toFixed(2)} MiB`);
  for (const row of summary) {
    console.log(
      `[cf-d1-seed] ${row.scope}: ${row.votaciones} votaciones, ${row.diputados} diputados, ${row.grupos} grupos`
    );
  }
}

main().catch((err) => {
  console.error(`[cf-d1-seed] ERROR: ${err?.message || err}`);
  process.exit(1);
});
